argoconfig:
  application:
    # -- Optional annotations to add to all Applications metadata.
    annotations: {}

# -- [Argo CD](https://argoproj.github.io/argo-cd/)
# @default -- [example](./examples/argocd.yaml)
argocd:
  # -- Enable Argo CD
  enabled: false
  name: argocd
  # -- Annotations for Argo CD app
  annotations: {}
  destination:
    # -- Namespace
    namespace: infra-argocd
  # -- Repo URL
  # @default -- [repo](https://argoproj.github.io/argo-helm)
  repoURL: https://argoproj.github.io/argo-helm
  # -- Chart
  chart: argo-cd
  # -- [argo-cd Helm chart](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd) version
  targetRevision: 7.7.5
  # -- Helm values
  # @default -- [upstream values](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml)
  values: {}

# -- [cert-manager](https://cert-manager.io/)
# @default -- [example](./examples/cert-manager.yaml)
certManager:
  # -- Enable cert-manager
  enabled: false
  name: certmgr
  # -- Annotations for cert-manager app
  annotations: {}
  destination:
    # -- Namespace
    namespace: infra-certmanager
  # -- Repo URL
  # @default -- [repo](https://charts.jetstack.io)
  repoURL: https://charts.jetstack.io
  # -- Chart
  chart: cert-manager
  # -- [cert-manager Helm chart](https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager) version
  targetRevision: 1.16.2
  # -- Helm values
  # @default -- [upstream values](https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml)
  values: {}

# -- [cert-manager-issuers](https://cert-manager.io/docs/configuration/)
# @default -- [example](./examples/cert-manager-issuers.yaml)
certManagerIssuers:
  # -- Enable cert-manager-issuers app
  enabled: false
  name: certmgr-issuers
  # -- Annotations for cert-manager-issuers app
  annotations: {}
  destination:
    # -- Namespace
    namespace: infra-certmanager
  # -- Repo URL
  # @default -- [repo](https://charts.adfinis.com)
  repoURL: https://charts.adfinis.com
  # -- Chart
  chart: cert-manager-issuers
  # -- [cert-manager-issuers Helm chart](https://github.com/adfinis/helm-charts/tree/main/charts/cert-manager-issuers) version
  targetRevision: 0.2.*
  # -- Helm values
  # @default -- [upstream values](https://github.com/adfinis/helm-charts/blob/main/charts/cert-manager-issuers/values.yaml)
  values: {}

# -- [cert-manager-monitoring](https://cert-manager.io/docs/configuration/)
# @default -- [example](./examples/cert-manager-monitoring.yaml)
certManagerMonitoring:
  # -- Enable cert-manager-monitoring
  enabled: false
  name: certmgr-monitoring
  # -- Annotations for cert-manager-monitoring app
  annotations: {}
  destination:
    # -- Namespace
    namespace: infra-certmanager
  # -- Repo URL
  # @default -- [repo](https://charts.adfinis.com)
  repoURL: https://charts.adfinis.com
  # -- Chart
  chart: cert-manager-monitoring
  # -- [cert-manager-monitoring Helm chart](https://github.com/adfinis/helm-charts/tree/main/charts/cert-manager-monitoring) version
  targetRevision: 0.1.*
  # -- Helm values
  # @default -- [upstream values](https://github.com/adfinis/helm-charts/blob/main/charts/cert-manager-monitoring/values.yaml)
  values: {}

ingressNginx:
  enabled: true
  name: ingress-nginx
  annotations: {}
  project: default
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  repoURL: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  targetRevision: 4.11.2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  values: {}
  valueFiles:
  - $values/charts/ingress-nginx/values.yaml
  externalValues: {
    repoURL: 'https://github.com/ekajsnosrap/infra-apps.git',
    targetRevision: HEAD,
    ref: values
  }

kubePrometheusStack:
  enabled: true
  name: monitoring
  annotations: {}
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  repoURL: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetRevision: 65.5.0
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  valueFiles:
  - $values/charts/kube-prometheus-stack/values.yaml
  externalValues: {
    repoURL: 'https://github.com/ekajsnosrap/infra-apps.git',
    targetRevision: HEAD,
    ref: values
  }